---
kind: Template
apiVersion: v1
metadata:
  name: deploy-sidecar
  annotations:
    openshift.io/display-name: Deploy Sidecar
    description: Deploy Sidecar
    iconClass: icon-openjdk
    tags: sidecar
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
      app: logtofile
    name: logtofile
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/wkulhanek/logtofile:latest
      from:
        kind: DockerImage
        name: docker.io/wkulhanek/logtofile:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
    generation: 2
    labels:
      app: logtofile
    name: logtofile
  spec:
    replicas: 1
    selector:
      app: logtofile
      deploymentconfig: logtofile
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
        creationTimestamp: null
        labels:
          app: logtofile
          deploymentconfig: logtofile
      spec:
        containers:
        - image: docker.io/wkulhanek/logtofile
          imagePullPolicy: Always
          name: logtofile
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - logtofile
        from:
          kind: ImageStreamTag
          name: logtofile:latest
          namespace: jnd-logging
        lastTriggeredImage: docker.io/wkulhanek/logtofile
      type: ImageChange

