apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
  labels:
    app: mlbparks
  name: mlbparks
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: tasks
    deploymentconfig: mlbparks
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
      labels:
        app: mlbparks
        deploymentconfig: mlbparks
    spec:
      containers:
        - image: 'docker-registry.default.svc:5000/mitzicom-dev/mlbparks:0.0-0'
          imagePullPolicy: IfNotPresent
          name: tasks
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /opt/eap/standalone/configuration/application-users.properties
              name: jboss-config
              subPath: application-users.properties
            - mountPath: /opt/eap/standalone/configuration/application-roles.properties
              name: jboss-config1
              subPath: application-roles.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config
        - configMap:
            defaultMode: 420
            name: tasks-config
          name: jboss-config1
  test: false
  triggers: []