apiVersion: v1
data:
  database-admin-password: bW9uZ29kYg==
  database-name: bW9uZ29kYg==
  database-password: bW9uZ29kYg==
  database-user: bW9uZ29kYg==
kind: Secret
metadata:
  labels:
    app: mongodb
  name: mongodb
type: Opaque