apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: nationalparks-dev-dc
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: nationalparks
    name: nationalparks
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: nationalparks
      deploymentconfig: nationalparks
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: nationalparks
          deploymentconfig: nationalparks
      spec:
        containers:
        - name: nationalparks
          image: " "
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_HOST
              value: mongodb
            - name: DB_PORT
              value: 27017
            - name: DB_USERNAME
              value: mongodb
            - name: DB_PASSWORD
              value: mongodb
            - name: DB_NAME
              value: parks
            - name: DB_REPLICASET
              value: rs0
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false




- env:
  - name: DB_HOST
    value: mongodb
  - name: DB_PORT
    value: 27017
  - name: DB_USERNAME
    value: mongodb
  - name: DB_PASSWORD
    value: mongodb
  - name: DB_NAME
    value: parks
  - name: DB_REPLICASET
    value: rs0