apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    name: mongodb
  name: mongodb
spec:
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    name: mongodb